import Head from 'next/head'
import Image from 'next/image'
import "../styles/globals.css"

export default function Home() {
  return (
    <>
      <Head>
        <title>Acme rockets</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="min-h-screen bg-slate-50 dark:bg-black dark:text-white ">
        <header className="bg-teal-700 text-white sticky top-0 z-10">
          <section className="max-w-4xl mx-auto p-5 flex justify-between items-center">

            <h1 className="text-3xl font-medium">
              <a href="#hero">
                🚀 Acme Rockets
              </a>
            </h1>
            <button id="mobile-open-btton" className="text-3xl sm:hidden focus:outline-none">
              &#9776;
            </button>
            <nav className="hidden sm:block space-x-8 text-xl" aria-label='main'>
              <a href="#rockets" className="hover:opacity-90">Our rockets</a>
              <a href="#testimonials" className="hover:opacity-90">Testimonials</a>
              <a href="#contact" className="hover:opacity-90">Contact</a>
            </nav>
          </section>
        </header>
        <main className="max-w-4cl mx-auto sm:scroll-smooth">
          <section id="hero" className="flex flex-col-reverse justify-center sm:flex-row px-6 items-center gap-8 mb-120 scroll-mt-40">
            <article className="sm:w-1/2">
              <h2 className="max-2-md text-4xl font-bold text-center sm:text-5sl sm:text-left text-slate-900 dark:text-white">
                We boldy go <span className="text-indigo-700 dark:text-indigo-300">where no rocket </span>  has gone before...
              </h2>
              <p className="max-w-md text-2xl mt-4 text-center sm:text-left text-slate-700 dark:text-slate-400">We &apos; re building rockets for the next century today. From the moon to Mars, Jupiter and beyond..</p>
              <p className="max-w-md text-2xl mt-4 text-center sm:text-left text-slate-700 dark:text-slate-400">Think Acme Rockets</p>
            </article>
            <Image src="/rocket1.jpg" alt="rocket taking off" width={200} height={200} />

          </section>

          <hr className="mx-auto bg-dark dark:bg-white w-1/2" />

          <section className="p-6 my-12 scroll-mt-20" id="rockets">
            <h2 className="text-4xl font-bold text-center sm:text-5xl mb-6 text-slate-900 dark:text-white">
              Our Rockets
            </h2>
            <ul className="list-none mx-auto my-12 flex flex-col sm:flex-row items-center gap-8">
              <li className="w-2/3 sm:w-5/6 flex flex-col items-center border border-solid border-slate-900 dark:border-gray-100 bg-white py-6 px-2 rounded-3xl shadow-xl dark:bg-black">
                <Image src={"/astronaut.jpg"} className="w-1/2" alt="astronaut" width={200} height={200} />
                <h3 className="text-3xl text-center text-slate-900 dark:text-white">
                  Explorer
                </h3>
                <p className="hidden sm:blocktext-3xl text-center mt-2 text-slate-500 dark:text-slate-400">
                  $
                </p>
                <p className="sm:hidden text-2xl text-center mt-2  text-slate-500 dark:text-slate-400">
                  Affordable Exploration
                </p>
              </li>
              <li className="w-2/3 sm:w-5/6 flex flex-col items-center border border-solid border-slate-900 dark:border-gray-100 bg-white py-6 px-2 rounded-3xl shadow-xl dark:bg-black">
                <Image src={"/rocketride.jpg"} className="w-1/2" alt="adventurer" width={200} height={200} />
                <h3 className="text-3xl text-center text-slate-900 dark:text-white">
                  Adventurer
                </h3>
                <p className="hidden sm:blocktext-3xl text-center mt-2 text-slate-500 dark:text-slate-400">
                  $$
                </p>
                <p className="sm:hidden text-2xl text-center mt-2  text-slate-500 dark:text-slate-400">
                  Best Selling Rocket!
                </p>
              </li>
              <li className="w-2/3 sm:w-5/6 flex flex-col items-center border border-solid border-slate-900 dark:border-gray-100 bg-white py-6 px-2 rounded-3xl shadow-xl dark:bg-black">
                <Image src={"/rocket-in-space.jpg"} className="w-1/2" alt="Infinity" width={200} height={200} />
                <h3 className="text-3xl text-center text-slate-900 dark:text-white">
                  Infinity
                </h3>
                <p className="hidden sm:blocktext-3xl text-center mt-2 text-slate-500 dark:text-slate-400">
                  $$$
                </p>
                <p className="sm:hidden text-2xl text-center mt-2  text-slate-500 dark:text-slate-400">
                  Luxury Starship
                </p>
              </li>
            </ul>
          </section>
          <hr className="mx-auto bg-dark dark:bg-white w-1/2" />


          <section className="p-6 my-12" id="testimonials">
            <h2 className="text-4xl font-bold text-center sm:text-5xl mb-6 text-slate-900 dark:text-white">
              Testimonials
            </h2>
          </section>
          <hr className="mx-auto bg-dark dark:bg-white w-1/2" />

          <section className="p-6 my-12" id="contact">
            <h2 className="text-4xl font-bold text-center sm:text-5xl mb-6 text-slate-900 dark:text-white">
              Contact us
            </h2>
          </section>


        </main>
      </div>
    </>
  )
}
