import Head from 'next/head'
import Image from 'next/image'
import "../styles/globals.css"

export default function Home() {
  return (
    <>
      <Head>
        <title>Acme rockets</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="min-h-screen bg-slate-50 dark:bg-black dark:text-white">
        <header className="bg-teal-700 text-white sticky top-0 z-10">
          <section className="max-w-4xl mx-auto p-5 flex justify-between items-center">

            <h1 className="text-3xl font-medium">
              <a href="#hero">
                🚀 Acme Rockets
              </a>
            </h1>
            <button id="mobile-open-btton" className="text-3xl sm:hidden focus:outline-none">
              &#9776;
            </button>
            <nav className="hidden sm:block space-x-8 text-xl" aria-label='main'>
              <a href="#rockets" className="hover:opacity-90">Our rockets</a>
              <a href="#testimonials" className="hover:opacity-90">Testimonials</a>
              <a href="#contact" className="hover:opacity-90">Contact</a>
            </nav>
          </section>
        </header>
        <main className="max-w-4cl mx-auto">
          <section id="hero" className="flex flex-col-reverse justify-center sm:flex-row px-6 items-center gap-8 mb-12">
            <article className="sm:w-1/2">

              <h2 className="max-2-md text-4xl font-bold text-center sm:text-5sl sm:text-left text-slate-900 dark:text-white">
                We boldy go <span className="text-indigo-700 dark:text-indigo-300">where no rocket </span>  has gone before...

              </h2>
              <p className="max-w-md text-2xl mt-4 text-center sm:text-left text-slate-700 dark:text-slate-400">We &apos; re building rockets for the next century today. From the moon to Mars, Jupiter and beyond..</p>
              <p className="max-w-md text-2xl mt-4 text-center sm:text-left text-slate-700 dark:text-slate-400">Think Acme Rockets</p>
            </article>
            <Image src="/rocket1.jpg" alt="rocket taking off" width={200} height={200} />

          </section>
        </main>
        <p>testing</p>
      </div>
    </>
  )
}
